#ifndef eWindowControlType_H
#define eWindowControlType_H

#include "Types.h"

enum eWindowControlType : uint8
{
	WINDOW_CONTROL_BUTTON,
	WINDOW_CONTROL_CHECK,
	WINDOW_CONTROL_DROP,
	WINDOW_CONTROL_EDIT,
	WINDOW_CONTROL_LIST,
	WINDOW_CONTROL_MENU,
	WINDOW_CONTROL_PROGRESS,
	WINDOW_CONTROL_RADIO,
	WINDOW_CONTROL_SCROLL,
	WINDOW_CONTROL_TEXT
};

#endif